name: Build and publish to npm registery

on:
  release:
    types: [created]
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: "17.x"
          cache: "pnpm"
          registry-url: "https://registry.npmjs.org"
          scope: "public"
      - run: pnpm install
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
